services:
  # Backend API
  backend:
    build:
      context: ./task-tracker-BE
      dockerfile: Dockerfile
    container_name: task_tracker_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb+srv://naelshayya1866:zXVxaT0XiHg9rBQz@taskmanager.e0narfx.mongodb.net/?retryWrites=true&w=majority&appName=TaskManager
      JWT_SECRET: your-jwt-secret-key-here
      FRONTEND_URL: http://localhost:3000

  # Frontend React App
  frontend:
    build:
      context: ./task-tracker
      dockerfile: Dockerfile
    container_name: task_tracker_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend